services:
  sadtalker:
    build: .
    container_name: sadtalker-env
    volumes:
      - .:/app/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    working_dir: /app/workspace
    command: tail -f /dev/null
